import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:geolocator/geolocator.dart';
import 'package:http/http.dart' as http;
import 'package:latlong2/latlong.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() { WidgetsFlutterBinding.ensureInitialized(); runApp(const App()); }

class App extends StatefulWidget { const App({super.key}); @override State<App> createState()=>_AppState(); }
class _AppState extends State<App> { bool dark=false; @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Noida Bus Tracker',themeMode:dark?ThemeMode.dark:ThemeMode.light,theme:ThemeData(useMaterial3:true,scaffoldBackgroundColor:const Color(0xFFF4F6F8),colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xFF111827))),darkTheme:ThemeData(useMaterial3:true,brightness:Brightness.dark,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xFFB8F26B),brightness:Brightness.dark)),home:Home(dark:dark,toggle:()=>setState(()=>dark=!dark))); }

class Home extends StatefulWidget { final bool dark; final VoidCallback toggle; const Home({super.key,required this.dark,required this.toggle}); @override State<Home> createState()=>_HomeState(); }

class _HomeState extends State<Home> {
 static const api='https://noida-bus-tracker.onrender.com';
 final map=MapController(); final search=TextEditingController(); Timer? refreshTimer,searchTimer;
 LatLng location=const LatLng(28.4598,77.5184); List<dynamic> buses=[]; List<dynamic> suggestions=[]; Set<String> favs={}; Map<String,List<LatLng>> history={}; List<LatLng> trail=[];
 double radius=5; bool loading=false,locating=false,movePin=false,stops=false,following=false,permissionBlocked=false; String? error,selected,followed; String locationLabel='Use your current location'; DateTime? refreshed;
 final stopData=const [['Botanical Garden',28.5640,77.3340],['Sector 37',28.5700,77.3450],['Noida City Center',28.5740,77.3560],['Sector 52',28.5890,77.3730],['Pari Chowk',28.4595,77.5082],['Chaar Murti',28.5650,77.4370],['Ek Murti',28.6040,77.4370],['Surajpur',28.5140,77.4830],['Kasna Village',28.4050,77.5060]];

 @override void initState(){super.initState();_prefs();WidgetsBinding.instance.addPostFrameCallback((_)=>_notice());}
 @override void dispose(){refreshTimer?.cancel();searchTimer?.cancel();search.dispose();super.dispose();}
 Future<void> _prefs() async { final p=await SharedPreferences.getInstance();if(mounted)setState(()=>favs=(p.getStringList('favs')??[]).toSet()); }
 Future<void> _notice() async { if(!mounted)return;await showDialog(context:context,barrierDismissible:false,builder:(c)=>AlertDialog(shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(24)),title:const Text('One important note'),content:const Text('Bus locations come from live GPS data. The “moving towards” information is an estimate from recent movement and can be wrong near junctions, turns or route changes.\n\nNot a government website.\nThis is an independent project made by a curious BTech student.\n\nData source: MARGDARSHI · UPSRTC',style:TextStyle(height:1.45)),actions:[FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Got it'))]));if(mounted)_location();}
 Future<void> _location() async { if(locating)return;setState(() { locating=true; error=null; permissionBlocked=false; });try{var p=await Geolocator.checkPermission();if(p==LocationPermission.denied)p=await Geolocator.requestPermission();if(p==LocationPermission.denied||p==LocationPermission.deniedForever){setState(() { permissionBlocked=p==LocationPermission.deniedForever; locationLabel=permissionBlocked?'Location permission is blocked':'Location permission is needed'; error=permissionBlocked?'Allow location permission from Android Settings.':'Allow location permission to find buses near you.'; });return;}if(!await Geolocator.isLocationServiceEnabled()){setState(() { locationLabel='Turn on location services'; error='Location services are turned off.'; });return;}final x=await Geolocator.getCurrentPosition(locationSettings:const LocationSettings(accuracy:LocationAccuracy.high));await _set(LatLng(x.latitude,x.longitude),'Current location',true);}catch(_){setState(() { locationLabel='Location unavailable'; error='Could not get your location. You can choose a point on the map.'; });}finally{if(mounted)setState(()=>locating=false);}}
 Future<void> _set(LatLng p,String label,bool load) async {setState(() { location=p; locationLabel=label; selected=null; error=null; });map.move(p,14.5);if(load){await _load();_auto();}}
 void _auto(){refreshTimer?.cancel();refreshTimer=Timer.periodic(const Duration(seconds:45),(_){if(!loading)_load(auto:true);});}
 Future<void> _load({bool auto=false}) async {if(loading)return;setState(()=>loading=true);final u=Uri.parse(api+'/api/buses/nearby?lat='+location.latitude.toString()+'&lon='+location.longitude.toString()+'&radius='+radius.toString());try{final r=await http.get(u).timeout(const Duration(seconds:20));if(r.statusCode!=200)throw Exception();final d=jsonDecode(r.body);final next=List<dynamic>.from(d['buses']??[]);for(final b in next){final id=''+b['bus_id'].toString();final a=double.tryParse(b['latitude'].toString());final o=double.tryParse(b['longitude'].toString());if(a==null||o==null)continue;history.putIfAbsent(id,()=>[]).add(LatLng(a,o));if(history[id]!.length>30)history[id]!.removeAt(0);}if(mounted)setState(() { buses=next; refreshed=DateTime.now(); error=null; });if(following&&followed!=null){final b=_find(followed!);if(b!=null)_center(b,false);}}catch(_){if(mounted)setState(()=>error='Unable to refresh bus data. Showing previous results.');}finally{if(mounted)setState(()=>loading=false);}}
 dynamic _find(String id){for(final b in buses){if(b['bus_id'].toString()==id)return b;}return null;}
 void _center(dynamic b,bool select){final a=double.tryParse(b['latitude'].toString()),o=double.tryParse(b['longitude'].toString());if(a==null||o==null)return;if(select)setState(()=>selected=b['bus_id'].toString());map.move(LatLng(a,o),16);}
 void _search(String v){searchTimer?.cancel();if(v.trim().length<2){setState(()=>suggestions=[]);return;}searchTimer=Timer(const Duration(milliseconds:350),()async{try{final r=await http.get(Uri.parse(api+'/api/search-location?q='+Uri.encodeQueryComponent(v))).timeout(const Duration(seconds:8));if(r.statusCode!=200)throw Exception();final d=jsonDecode(r.body);if(mounted)setState(()=>suggestions=List<dynamic>.from(d['results']??[]));}catch(_){if(mounted)setState(()=>suggestions=[]);}});}
 Future<void> _pick(dynamic x)async{final a=double.tryParse(x['latitude'].toString()),o=double.tryParse(x['longitude'].toString());if(a==null||o==null)return;search.text=x['name'].toString();FocusScope.of(context).unfocus();setState(()=>suggestions=[]);await _set(LatLng(a,o),x['name'].toString(),true);}
 void _tap(TapPosition _,LatLng p){if(!movePin)return;_set(p,'Selected map location',true);setState(()=>movePin=false);}
 Future<void> _fav(String id)async{final n=Set<String>.from(favs);n.contains(id)?n.remove(id):n.add(id);final p=await SharedPreferences.getInstance();await p.setStringList('favs',n.toList());if(mounted)setState(()=>favs=n);}
 void _follow(dynamic b){final id=b['bus_id'].toString();setState(() { followed=followed==id?null:id; following=followed!=null; });_center(b,true);}
 void _trail(dynamic b){final p=history[b['bus_id'].toString()]??[];if(p.length<2){_info('Trail needs a few refreshes first.');return;}setState(()=>trail=List<LatLng>.from(p));map.fitCamera(CameraFit.coordinates(coordinates:trail,padding:const EdgeInsets.all(45)));}
 void _play(dynamic b){final p=history[b['bus_id'].toString()]??[];if(p.length<2){_info('Playback needs a few recorded positions first.');return;}var i=0;Timer.periodic(const Duration(milliseconds:450),(t){if(!mounted||i>=p.length){t.cancel();return;}map.move(p[i++],16);});}
 void _eta(dynamic b){final s=double.tryParse(b['speed'].toString())??0,d=double.tryParse(b['distance_km'].toString())??0;if(s<3){_info('Approx ETA unavailable while this bus is stationary or very slow.');return;}_info('Approx ETA: '+(d/s*60).ceil().toString()+' min\nDistance: '+d.toStringAsFixed(2)+' km\nBased on current/recent GPS speed.');}
 void _share(dynamic b){Clipboard.setData(ClipboardData(text:'Noida Bus Tracker · Bus '+b['bus_id'].toString()));_info('Bus ID copied to clipboard.');}
 void _report(dynamic b){showModalBottomSheet(context:context,showDragHandle:true,builder:(c)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[Padding(padding:const EdgeInsets.all(16),child:Text('Report '+b['bus_id'].toString(),style:const TextStyle(fontSize:20,fontWeight:FontWeight.w800))),...['Not moving','Wrong location','Already passed','Crowded'].map((x)=>ListTile(title:Text(x),leading:const Icon(Icons.flag_outlined),onTap:(){Navigator.pop(c);_info('Thanks. Your report has been noted locally.');}))])));}
 void _info(String s){if(!mounted)return;showDialog(context:context,builder:(c)=>AlertDialog(title:const Text('Noida Bus Tracker'),content:Text(s),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('OK'))]));}
 void _settings(){showModalBottomSheet(context:context,showDragHandle:true,builder:(c)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[const Padding(padding:EdgeInsets.all(16),child:Text('App settings',style:TextStyle(fontSize:21,fontWeight:FontWeight.w800))),ListTile(leading:const Icon(Icons.dark_mode_outlined),title:const Text('Dark mode'),trailing:Switch(value:widget.dark,onChanged:(_){Navigator.pop(c);widget.toggle();})),ListTile(leading:const Icon(Icons.notifications_none),title:const Text('Nearby bus alerts'),subtitle:const Text('Proximity alerts can be added with background location support')),ListTile(leading:const Icon(Icons.info_outline),title:const Text('About'),onTap:()=>_info('Independent project by a curious BTech student.\nLive GPS data: MARGDARSHI · UPSRTC.'))])));}
 @override Widget build(BuildContext context){return Scaffold(appBar:AppBar(title:const Row(children:[Icon(Icons.directions_bus_rounded),SizedBox(width:8),Text('Noida Bus Tracker',style:TextStyle(fontWeight:FontWeight.w800))]),actions:[IconButton(onPressed:(){showModalBottomSheet(context:context,showDragHandle:true,builder:(c)=>ListView(padding:const EdgeInsets.all(16),children:[const Text('Favourite buses',style:TextStyle(fontSize:21,fontWeight:FontWeight.w800)),...buses.where((b)=>favs.contains(b['bus_id'].toString())).map((b)=>ListTile(title:Text(b['bus_id'].toString()),subtitle:Text((b['distance_km']??'?').toString()+' km away'),onTap:(){Navigator.pop(c);_center(b,true);})),if(buses.where((b)=>favs.contains(b['bus_id'].toString())).isEmpty)const Padding(padding:EdgeInsets.all(24),child:Text('No favourite buses nearby.'))]));},icon:const Icon(Icons.star_border)),IconButton(onPressed:_settings,icon:const Icon(Icons.settings_outlined)),Container(margin:const EdgeInsets.only(right:12,top:12,bottom:12),padding:const EdgeInsets.symmetric(horizontal:9),alignment:Alignment.center,decoration:BoxDecoration(color:const Color(0xFFEAF8EF),borderRadius:BorderRadius.circular(20)),child:const Text('LIVE',style:TextStyle(fontSize:10,fontWeight:FontWeight.w800,color:Color(0xFF15803D))))]),body:RefreshIndicator(onRefresh:_load,child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.fromLTRB(16,8,16,30),children:[_locationCard(),const SizedBox(height:12),_searchCard(),const SizedBox(height:12),_mapCard(),const SizedBox(height:14),_header(),if(error!=null)_error(),if(loading&&buses.isEmpty)const Padding(padding:EdgeInsets.all(30),child:Center(child:CircularProgressIndicator())),if(!loading&&buses.isEmpty&&error==null)_empty(),...buses.map(_card),const SizedBox(height:18),const Text('Independent project. Not a government website.\nLive GPS data sourced from MARGDARSHI · UPSRTC.',textAlign:TextAlign.center,style:TextStyle(color:Color(0xFF6B7280),fontSize:11,height:1.5))])));}
 Widget _locationCard(){return Card(elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(24)),child:Padding(padding:const EdgeInsets.all(17),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('START HERE',style:TextStyle(fontSize:11,fontWeight:FontWeight.w800,letterSpacing:1.1,color:Color(0xFF6B7280))),const SizedBox(height:5),const Text('Find buses near you',style:TextStyle(fontSize:22,fontWeight:FontWeight.w800)),const SizedBox(height:4),Text(locationLabel,style:const TextStyle(color:Color(0xFF6B7280))),const SizedBox(height:13),SizedBox(width:double.infinity,height:50,child:FilledButton.icon(onPressed:locating?null:_location,icon:locating?const SizedBox(width:19,height:19,child:CircularProgressIndicator(strokeWidth:2,color:Colors.white)):const Icon(Icons.my_location_rounded),label:Text(locating?'Getting location…':'Use current location'))),if(permissionBlocked)OutlinedButton.icon(onPressed:Geolocator.openAppSettings,icon:const Icon(Icons.settings_outlined),label:const Text('Open location settings')),const SizedBox(height:8),Row(children:[const Icon(Icons.radar_rounded,size:18),const SizedBox(width:7),const Text('Search radius',style:TextStyle(fontWeight:FontWeight.w600)),const Spacer(),DropdownButtonHideUnderline(child:DropdownButton<double>(value:radius,items:const[DropdownMenuItem(value:1,child:Text('1 km')),DropdownMenuItem(value:3,child:Text('3 km')),DropdownMenuItem(value:5,child:Text('5 km')),DropdownMenuItem(value:10,child:Text('10 km')),DropdownMenuItem(value:15,child:Text('15 km'))],onChanged:(v){if(v!=null){setState(()=>radius=v);_load();}}))])])));}
 Widget _searchCard(){return Card(elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(20)),child:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(15,5,8,5),child:Row(children:[const Icon(Icons.search_rounded),const SizedBox(width:8),Expanded(child:TextField(controller:search,onChanged:_search,decoration:const InputDecoration(hintText:'Search Sector 62, Pari Chowk, Botanical Garden…',border:InputBorder.none))),if(search.text.isNotEmpty)IconButton(onPressed:(){search.clear();setState(()=>suggestions=[]);},icon:const Icon(Icons.close))])),...suggestions.map((x)=>ListTile(leading:const Icon(Icons.place_outlined),title:Text(x['name'].toString()),onTap:()=>_pick(x))) ]));}
 Widget _mapCard(){final ms=<Marker>[];for(final b in buses){final a=double.tryParse(b['latitude'].toString()),o=double.tryParse(b['longitude'].toString());if(a==null||o==null)continue;final id=b['bus_id'].toString(),sel=id==selected;ms.add(Marker(point:LatLng(a,o),width:sel?54:48,height:sel?54:48,child:GestureDetector(onTap:()=>_center(b,true),child:Container(decoration:BoxDecoration(color:sel?const Color(0xFFB8F26B):const Color(0xFF111827),shape:BoxShape.circle,border:Border.all(color:Colors.white,width:3),boxShadow:const[BoxShadow(color:Color(0x33000000),blurRadius:8)]),child:Icon(Icons.directions_bus_rounded,color:sel?Colors.black:Colors.white,size:22))))));}ms.add(Marker(point:location,width:40,height:40,child: Container(decoration:BoxDecoration(color:const Color(0xFF2563EB),shape:BoxShape.circle,border:Border.all(color:Colors.white,width:4)),child:const Icon(Icons.my_location_rounded,color:Colors.white,size:18))));if(stops)for(final s in stopData)ms.add(Marker(point:LatLng(s[1] as double,s[2] as double),width:32,height:32,child:Tooltip(message:s[0] as String,child:const Icon(Icons.location_on,color:Color(0xFFB45309),size:27))));return Card(elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(24)),clipBehavior:Clip.antiAlias,child:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(12,10,6,7),child:Row(children:[const Expanded(child:Text('LIVE MAP',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800))),IconButton(onPressed:()=>setState(()=>stops=!stops),icon:Icon(stops?Icons.visibility:Icons.location_on_outlined)),IconButton(onPressed:_location,icon:const Icon(Icons.my_location)),IconButton(onPressed:()=>setState(()=>movePin=!movePin),icon:Icon(movePin?Icons.pin_drop:Icons.edit_location_alt)),if(trail.isNotEmpty)IconButton(onPressed:()=>setState(()=>trail=[]),icon:const Icon(Icons.clear))])),if(movePin)const Text('Tap the map to choose a new location',style:TextStyle(fontSize:12,color:Color(0xFF6B7280))),SizedBox(height:340,child:FlutterMap(mapController:map,options:MapOptions(initialCenter:location,initialZoom:12.5,onTap:_tap),children:[TileLayer(urlTemplate:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',userAgentPackageName:'com.example.noida_bus_tracker'),if(trail.length>1)PolylineLayer(polylines:[Polyline(points:trail,strokeWidth:5)]),MarkerLayer(markers:ms)]))]));}
 Widget _header(){final t=refreshed==null?'Waiting for a location':'Updated '+refreshed!.hour.toString().padLeft(2,'0')+':'+refreshed!.minute.toString().padLeft(2,'0')+' · Auto refresh 45s';return Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Nearby electric buses',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),Text(t,style:const TextStyle(fontSize:12,color:Color(0xFF6B7280)))])),IconButton(onPressed:loading?null:_load,icon:const Icon(Icons.refresh))]);}
 Widget _card(dynamic b){final id=b['bus_id'].toString(),speed=double.tryParse(b['speed'].toString()),dist=double.tryParse(b['distance_km'].toString()),dir=b['likely_towards'];return Card(elevation:selected==id?3:0,margin:const EdgeInsets.only(top:10),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(20),side:BorderSide(color:selected==id?const Color(0xFFB8F26B):Theme.of(context).dividerColor)),child:InkWell(onTap:()=>_center(b,true),child:Padding(padding:const EdgeInsets.all(15),child:Column(children:[Row(children:[Container(width:50,height:50,decoration:BoxDecoration(color:Theme.of(context).colorScheme.surfaceContainerHighest,borderRadius:BorderRadius.circular(15)),child:const Icon(Icons.directions_bus,size:26)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(id,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w800)),Wrap(spacing:10,children:[if(dist!=null)Text(dist.toStringAsFixed(2)+' km',style:const TextStyle(fontSize:12,color:Color(0xFF6B7280))),if(speed!=null)Text(speed.toStringAsFixed(0)+' km/h',style:const TextStyle(fontSize:12,color:Color(0xFF6B7280))),Text((b['vehicle_status']??'Status unknown').toString(),style:const TextStyle(fontSize:12,color:Color(0xFF6B7280)))])])),IconButton(onPressed:()=>_fav(id),icon:Icon(favs.contains(id)?Icons.star:Icons.star_border,color:favs.contains(id)?const Color(0xFFB45309):null))]),if(dir is String&&dir.isNotEmpty)Padding(padding:const EdgeInsets.only(top:9),child:Row(children:[const Icon(Icons.trending_flat,size:20),const SizedBox(width:7),Expanded(child:Text('Moving towards '+dir,style:const TextStyle(fontWeight:FontWeight.w700)))])),const SizedBox(height:9),Wrap(spacing:6,runSpacing:6,children:[_chip('ETA',Icons.timer_outlined,()=>_eta(b)),_chip(followed==id&&following?'Following':'Follow',Icons.center_focus_strong,()=>_follow(b)),_chip('Trail',Icons.route_outlined,()=>_trail(b)),_chip('Playback',Icons.play_arrow,()=>_play(b)),_chip('Share',Icons.share_outlined,()=>_share(b)),_chip('Report',Icons.flag_outlined,()=>_report(b))])]))));}
 Widget _chip(String s,IconData i,VoidCallback f)=>ActionChip(avatar:Icon(i,size:16),label:Text(s),onPressed:f);
 Widget _error()=>Card(color:const Color(0xFFFFF7ED),child:Padding(padding:const EdgeInsets.all(12),child:Row(children:[const Icon(Icons.warning_amber,color:Color(0xFFB45309)),const SizedBox(width:8),Expanded(child:Text(error!,style:const TextStyle(color:Color(0xFF92400E),fontSize:12,fontWeight:FontWeight.w600)))]));
 Widget _empty()=>const Card(child:Padding(padding:EdgeInsets.all(28),child:Column(children:[Icon(Icons.directions_bus_outlined,size:44,color:Color(0xFF9CA3AF)),SizedBox(height:10),Text('No buses found nearby',style:TextStyle(fontWeight:FontWeight.w800)),SizedBox(height:5),Text('Try increasing the radius or choosing another location.',textAlign:TextAlign.center,style:TextStyle(color:Color(0xFF6B7280),fontSize:13))]));
}